[masters]
10.0.58.39
10.0.79.207
10.0.81.97

[workers]
10.0.56.25
10.0.77.201

[k8s_cluster:children]
masters
workers

[all:vars]
ansible_user=ec2-user
ansible_ssh_private_key_file=~/.ssh/id_ed25519
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
